### ISSUE TITLE
Feature: Endpoint sorting

### ISSUE THREAD

**Issue by aleixmorgadas** [vlingo/vlingo-http#12]
Allow unsorted endpoints for the developer (from specific to generic is required now).

### Current Behaviour

Defined the next endpoints in the specific order

1. GET `/users`
2. GET `/users/all`

When it's performed the call

- GET `/users/all`, the 1. method is resolved first

### Desired behaviour

It should be called the 2. method resolver

**Comment by VaughnVernon** [comment]
There is a configuration `disallowPathParametersWithSlash` that may be associated with each `Resource` and that could possibly fix the apparent problem of unprioritized patterns. I haven't tried it in your use case, so I am not certain. I have considered this to default to true since it's almost always applicable. See `Action` for path matching to see how it's used.
