### ISSUE TITLE
Gson deserialize without mappers

### ISSUE THREAD

**Issue by bwehrle** [vlingo/vlingo-http#22]
Hi,
I noticed that if I made a class such as 
````
class Bar {
  private final int val;
 public Bar(int val) {this.val = val;}
}
``````
I could create a Resource like this:
````
post("/foo").body(Bar.class).handle(this::createFoo),
`````
with
`````
void createFoo(Bar b) {
}
`````
Now, I can make a post that will be accepted with the data:
`````
{val: "12345"}
``````
This works as expected.
However, if I do the following:
`````
{somekey: "12345"}
``````
I will get a Bar with a val == 0.  I would expect the resource handler to automatically throw a 404, since the data does not conform to the expected requirements (my class cannot be constructed  with the data presented).

I see there is a provision for adding mappers, which I assume solves this problem, but this default case is not safe; the client code cannot determine if the value was actually "0", and in fact my ctor for Bar is never called, due to how gson is implemented. 

Leaving the  methods without mappers the use, in my opinion, is presenting an unsafe interface,  given how gson works by default via "unsafe" object construction.   So, in other terms, this default behaviour by-passes the invariance rules in my value objects.  I question whether  it is useful  the developer to  expose these interfaces as-is, since it is not evident this  problem can arise. 

https://medium.com/@programmerr47/gson-unsafe-problem-d1ff29d4696f

**Comment by aleixmorgadas** [comment]
Hi @bwehrle,

The mapping feature is still undone, I'd opened the #14 (Optional Mapper) to inform that it still needs work to be done. Thanks for reporting ^^

Meanwhile using `file configuration` it's possible, with `FluentAPI` you cannot define _custom mappers_ yet.

I'm currently doing a feature with more priority than this one (one thing a time :smile:). I would love if you could help us here ^^ I could guide you though the FluentAPI, I think it's still small, so it should be fast to become familiar with.

In case this issue is solved with #14, please, feel free to close it, or move the conversation there :)

**Comment by VaughnVernon** [comment]
@brian-wehrle-roche As @aleixmorgadas note, this should be handled in #14 and I have made comments on the possible solutions over there.

**Comment by bwehrle** [comment]
Hi @aleixmorgadas, @VaughnVernon ,
Thanks for the feedback.  I'd be happy to help-  I´ll join the channel.  Let me know what needs to be done; we can close this as a dupe of #14, and cover any additional items needed there.
