### ISSUE TITLE
Server shutdown() always fails

### ISSUE THREAD

**Issue by bwehrle** [vlingo/vlingo-http#25]
The test code in ServerTest.java  apparently hints at this case.  The code will always return false and spend as much time as the specified await time.  Probably better to remove this and just have people call server.stop(), or fix.  There should be some documentation that informs of the benefit of using shutdown (graceful completion of in-flight work?)
```
  @After
  public void tearDown() {
    client.close();
    server.shutDown(); // TODO: wait
//    if (!server.shutDown().await(2000)) {
//      System.out.println("Server did not shut down properly.");
//    }
    super.tearDown();
  }
```

**Comment by aleixmorgadas** [comment]
@VaughnVernon, do you know the reason? IRRC, we need the `shutDown` method to return `Completes<Boolean>` because of the ports usage on some tests.

The case was, the test suit started a couple `Server` instances, then, when we called `tearDown`, the port wasn't freed when the next test required to start a new `Server` on the same port, so, test suit failed randomly. I think, eventually, we moved into random port instead of a fixed one.

**Comment by jakzal** [comment]
`ServerTest`s use random port numbers now: https://github.com/vlingo/vlingo-http/blob/efb7c895e8c7605a88f3b0d92b013974d184af50/src/test/java/io/vlingo/http/resource/ServerTest.java#L251

Is there anything else left to do here?

**Comment by VaughnVernon** [comment]
No, it's just been dangling for two years 😉
