### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by VaughnVernon** [vlingo/vlingo-http#32]
Please see https://github.com/vlingo/vlingo-wire/issues/6

**Comment by VaughnVernon** [comment]
We need vlingo/http servers to support SSL/HTTPS. We need vlingo/http non-blocking clients to be able to access SSL/HTTPS servers.

Please see additional information on examples:
https://groups.google.com/forum/#!searchin/conscrypt/example%7Csort:date/conscrypt/T4c2YCY91qc/2tkxgHcTBAAJ

> Conscrypt is a JCA security provider, so for the most part you just use the standard JCA APIs. 
https://docs.oracle.com/javase/9/security/java-cryptography-architecture-jca-reference-guide.htm

> For your specific example, see:
https://stackoverflow.com/questions/11787571/how-to-read-pem-file-to-get-private-and-public-key.

**Comment by aleixmorgadas** [comment]
To add SSL support we need to touch two components, [http](https://github.com/vlingo/vlingo-http) and [wire](https://github.com/vlingo/vlingo-wire).

For **vlingo-http**, I would start checking the next two classes:

- [Server](https://github.com/vlingo/vlingo-http/blob/master/src/main/java/io/vlingo/http/resource/Server.java)
- [ServerActor](https://github.com/vlingo/vlingo-http/blob/master/src/main/java/io/vlingo/http/resource/ServerActor.java)

Since what people use is vlingo-http, we need here the way to enable the SSL/HTTPS support.

vlingo-http delegate the actual `Server` implementation into [vlingo-wire](https://github.com/vlingo/vlingo-wire) component/module. For `wire`, I would start checking the direct class used by `ServerActor`:

- [ServerRequestResponseChannel](https://github.com/vlingo/vlingo-wire/blob/master/src/main/java/io/vlingo/wire/fdx/bidirectional/ServerRequestResponseChannel.java)
- [ServerRequestResponseChannelActor](https://github.com/vlingo/vlingo-wire/blob/master/src/main/java/io/vlingo/wire/fdx/bidirectional/ServerRequestResponseChannelActor.java), it contains the `java.nio.channels.ServerSocketChannel`

I think it should be possible to enable the SSL using those classes, or those plus the used by them.

If more information is needed, please, don't hesitate to post your question ^^

**Comment by VaughnVernon** [comment]
From discussions with @aleixmorgadas and @kmruiz it seems best to postpone this indefinitely or at least until we have strong proof that it is needed. We have decided that this kind of support should be provided by existing tools such as `NGINX`, `CloudFront`, etc., and that `vlingo/http` is best served by focusing on fluent tooling for DDD-based use cases.

**Comment by VaughnVernon** [comment]
@aleixyz You can now see an issue here https://github.com/vlingo/vlingo-wire/issues/6 that indicates how this can be achieved with NIO.

**Comment by VaughnVernon** [comment]
Implemented/Fixed with: https://github.com/vlingo/vlingo-wire/issues/6
