### ISSUE TITLE
Eliminate Bare TestUntil Uses

### ISSUE THREAD

**Issue by VaughnVernon** [vlingo/vlingo-http#33]
The following tests must be converted to use `AccessSafely` rather than bare `TestUntil`:

- ~~MockResponseSenderChannel (mock used by tests)~~
- ~~SseFeedTest~~
- ~~SseStreamResourceTest~~
- ~~ClientTest~~
- ~~ConfigurationResourceTest~~
- ~~MockCompletesEventuallyResponse (mock used by tests)~~
- ~~ServerTest~~
- ~~TestResponseChannelConsumer (used by tests)~~

**Comment by GregLoring** [comment]
In summary AccessSafely is necessary to ensure that multiple threads see the same state when a test is executed. With the current use of TestUntil only the test case thread and the thread under test can see different values due to the way threads are managed by the Java Memory Model.

Examples
Here are some examples of tests that have already been refactored to use AccessSafely so you can see how it works.

(1) Note the use of MockServiceDiscoveryInterest by DirectoryServiceTest. The use of AccessSafely is inside MockServiceDiscoveryInterest:
https://github.com/vlingo/vlingo-directory/blob/master/src/test/java/io/vlingo/directory/model/DirectoryServiceTest.java

https://github.com/vlingo/vlingo-directory/blob/master/src/test/java/io/vlingo/directory/client/MockServiceDiscoveryInterest.java

(2) Note the use of MockJournalListener by ForumTest. The use of AccessSafely is inside MockJournalListener:
https://github.com/vlingo/vlingo-examples/blob/master/vlingo-iddd-collaboration/src/test/java/com/saasovation/collaboration/model/forum/ForumTest.java

https://github.com/vlingo/vlingo-examples/blob/master/vlingo-iddd-collaboration/src/test/java/com/saasovation/collaboration/model/MockJournalListener.java

**Comment by VaughnVernon** [comment]
This was fixed back in June and was not closed.
