### ISSUE TITLE
ResourceBuilder should treat trailing slash optional

### ISSUE THREAD

**Issue by hurelhuyag** [vlingo/vlingo-http#73]
I believe that trailing slash "/" character should be optional in every request URL. For instance below example URL should treated same.
```
http://localhost:18080/veterinarians/{id}/
http://localhost:18080/veterinarians/{id}
```

Currently if I use route like below snippet and call this endpoint with `http://localhost:18080/veterinarians/abc/`. `this::veterinarian` method receiving variable `id=abc/`. It must be `id=abc` (without trailing slash)
```
  @Override
  public Resource<?> routes() {
     return resource("VeterinarianResource",
        io.vlingo.http.resource.ResourceBuilder.get("/veterinarians/{id}")
            .param(String.class)
            .handle(this::veterinarian)
     );
  }
```

**Comment by VaughnVernon** [comment]
@hurelhuyag We support the Google interpretation of this. The trailing `/` indicates a directory, and as such, we first attempt to serve the default content for a directory, namely `index.html`. If the default resource is not there then the response is a 404.

If you don't want this behavior then please don't place a `/` at the end of a URL. Besides, if the ending `/` follows a static file resource, or any other logical resource such as `/resources/{id}/` rather than `/resources/{id}`, what would be the purpose?

https://developers.google.com/search/blog/2010/04/to-slash-or-not-to-slash

**Comment by hurelhuyag** [comment]
Ok. Then which one is correct for our use case. `http://localhost:18080/veterinarians` or `http://localhost:18080/veterinarians/`?

**Comment by VaughnVernon** [comment]
Assuming that  `http://localhost:18080/veterinarians` is meant to be a resource that is a collection of all individual `veterinarians` resources, then it is the correct URL.

This URL `http://localhost:18080/veterinarians/` would indicate that there is a directory named `veterinarians`, and we would attempt to read the `index.html` from that directory. That I am sure would fail with a 404.

**Comment by hurelhuyag** [comment]
Ok. I remembered something from xoom-starter. According to that rule, This uneditable trailing slash must be eliminated. Right?

![Screenshot from 2021-03-16 11-45-40](https://user-images.githubusercontent.com/1059242/111253000-51eca880-864d-11eb-96ea-b86b17b7481e.png)

**Comment by VaughnVernon** [comment]
> Ok. I remembered something from xoom-starter. According to that rule, This uneditable trailing slash must be eliminated. Right?
> 
> Ok. I remembered something from xoom-starter. According to that rule, This uneditable trailing slash must be eliminated. Right?

Yes, I agree. I have asked numerous times for that change. I thought it had already been made. Perhaps @danilo-ambrosio has already made that change but not built the new binary artifact.

Would you please check and see if the change has been made? If not, please attempt to fix it and request @abdullahcalisir12 to review. Otherwise if it seems too difficult, please ask @abdullahcalisir12 to make the change.

**Comment by VaughnVernon** [comment]
The URL editing issue was fixed.
